/* Standard plugins */
plugins {
    id 'java'
    id 'maven-publish'
    id 'jacoco'
}

/* Maven repositories */
repositories {
    mavenLocal()
    mavenCentral()
}

tasks.withType(JavaCompile) {
    options.deprecation = true
    options.encoding = 'UTF-8'
    options.release = 21
}
tasks.withType(Javadoc).all {
    enabled = false
}

/* Build source and javaDoc jars */
java {
    //withJavadocJar()
    withSourcesJar()
}

/* Support jUnit 5 */
testing {
    suites {
        test {
            useJUnitJupiter()

            targets {
                all {
                    testTask.configure {
                        maxHeapSize = '4g'
                    }
                }
            }
        }
    }
}

/* Add annotations */
dependencies {
    compileOnly "org.jetbrains:annotations:26.1.0"
}

/* Java options */
compileJava {
    options.compilerArgs += ["-Xlint:unchecked"]
}

/* Maven publishing */
publishing {
    publications {
        maven(MavenPublication) {
            from(components.java)
        }
    }
}

/* Jacoco */
test {
    finalizedBy jacocoTestReport
}
jacocoTestReport {
    dependsOn test
}
jacoco {
    toolVersion = "0.8.15"
}

/* Project properties */
ext {
    /* Manifest Attributes */
    manifestAttrs = rootProject.ext.baseManifest.clone()

    /* manifest control */
    mainClass = null
    moduleName = null
    preLoaderClass = null
    splashScreen = null
}

processResources {
    filesMatching("**/*.properties") {
        expand(
            "MyName": "${rootProject.ext.MyName}",
            "inceptionYear": "${rootProject.ext.inceptionYear}",
            "currentYear": "${rootProject.ext.currentYear}",
            "buildTimestamp": "${rootProject.ext.buildTimestamp}",
            "buildNumber": "${rootProject.ext.gitRev}",
            "projectVersion": "${rootProject.ext.projectVersion}"
        )
    }
}
