/* javaFX Specifics */
plugins {
    id 'jOceanus-java'
    id 'jOceanus-javafx'
    id 'org.openjfx.javafxplugin' version "0.1.0"
}

/* javaFX versions */
javafx {
    modules = [ 'javafx.web', 'javafx.controls', 'javafx.graphics' ]
}

/* Dependencies */
dependencies {
    implementation platform(project(':bom'))
    implementation project(':tethys-core')
    implementation project(':tethys-api')
    implementation project(':oceanus')
}

/* Description */
group = 'io.github.tonywasher.joceanus.tethys'
description = 'Tethys JavaFX Utilities'

/* Register the project */
rootProject.registerProject(project)

/* Specific Manifest details */
jar {
    manifest {
        attributes(manifestAttrs)
    }
}
