/* javaFX Specifics */
plugins {
    id 'jOceanus-java'
    id 'jOceanus-javafx'
    id 'org.openjfx.javafxplugin' version "0.1.0"
}

/* Dependencies */
dependencies {
    implementation platform(project(':bom'))
    implementation project(':tethys-core')
    implementation project(':tethys-api')
    implementation project(':tethys-javafx')
    implementation project(':tethys-swing')
    implementation project(':oceanus')
    implementation "org.jfree:jfreechart"
}

/* Description */
group = 'io.github.tonywasher.joceanus.tethys'
description = 'Tethys UI Test'

/* Register the project */
rootProject.registerProject(project)

/* Specific Manifest details */
jar {
    manifest {
        attributes(manifestAttrs)
    }
}
