#
# Themis: Java Project Framework
# Copyright 2026. Tony Washer
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.  You may obtain a copy
# of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
# License for the specific language governing permissions and limitations under
# the License.
#

##
## Data Source.
##
Themis.data.source=Source

##
## Data Solver.
##
Themis.data.solver=Solver

##
## Data Stats.
##
Themis.data.stats=Stats

##
## Data Name.
##
Themis.data.name=Name

##
## Data Project.
##
Themis.data.project=Project

##
## Data Module.
##
Themis.data.module=Module

##
## Data Modules.
##
Themis.data.modules=Modules

##
## Data Packages.
##
Themis.data.packages=Packages

##
## Data Files.
##
Themis.data.files=Files

##
## Data Class.
##
Themis.data.class=Class

##
## Data Classes.
##
Themis.data.classes=Classes

##
## Data Methods.
##
Themis.data.methods=Methods

##
## Data Parent.
##
Themis.data.parent=Parent

##
## Data Children.
##
Themis.data.children=Children

##
## Data Underlying.
##
Themis.data.underlying=Underlying

##
## Data Totals.
##
Themis.data.totals=Totals

##
## Data referType.
##
Themis.data.refType=RefType

##
## Data references.
##
Themis.data.references=References

##
## Data referenced.
##
Themis.data.referenced=Referenced

##
## Data localRefs.
##
Themis.data.localRefs=LocalRefs

##
## Data impliedRefs.
##
Themis.data.impliedRefs=ImpliedRefs

##
## Data standard.
##
Themis.data.standard=Standard

##
## Data circular.
##
Themis.data.circular=Circular

##
## Data incestuous.
##
Themis.data.incestuous=Incestuous

##
## Data groupId.
##
Themis.data.groupId=GroupId

##
## Data artifactId.
##
Themis.data.artifactId=ArtifactId

##
## Data version.
##
Themis.data.version=Version

##
## Data classifier.
##
Themis.data.classifier=Classifier

##
## Data scope.
##
Themis.data.scope=Scope

##
## Data optional.
##
Themis.data.optional=Optional

##
## Data id.
##
Themis.data.id=Id

##
## Data properties.
##
Themis.data.properties=Properties

##
## Data xtraDirs.
##
Themis.data.xtraDirs=XtraDirs

##
## Data versions.
##
Themis.data.versions=Versions

##
## Data directDependencies.
##
Themis.data.directDependencies=DirectDependencies

##
## Data dependencies.
##
Themis.data.dependencies=Dependencies

##
## Data parsedModules.
##
Themis.data.parsedModules=ParsedModules
