#
# Themis: Java Project Framework
# Copyright 2026. Tony Washer
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.  You may obtain a copy
# of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
# License for the specific language governing permissions and limitations under
# the License.
#

##
## References Tab.
##
Themis.ui.tab.source=Source

##
## References Tab.
##
Themis.ui.tab.references=References

##
## Statistics Tab.
##
Themis.ui.tab.stats=Statistics

##
## Log Tab.
##
Themis.ui.tab.log=Log

##
## Project title.
##
Themis.ui.select.project=Select Project

##
## Project prompt.
##
Themis.ui.prompt.project=Project:

##
## Module prompt.
##
Themis.ui.prompt.module=Module:

##
## Package prompt.
##
Themis.ui.prompt.package=Package:

##
## File prompt.
##
Themis.ui.prompt.file=File:

##
## Local Package.
##
Themis.ui.package.local=<Local>

##
## Root Package.
##
Themis.ui.package.root=<Root>

##
## Family Package.
##
Themis.ui.package.family=<Family>

##
## Annotation Name.
##
Themis.ui.source.decl.annot=Annotation

##
## Annotation Member Name.
##
Themis.ui.source.decl.annotMember=AnnotationMember

##
## Compact Name.
##
Themis.ui.source.decl.compact=Compact

##
## Constructor Name.
##
Themis.ui.source.decl.construct=Constructor

##
## Field Name.
##
Themis.ui.source.decl.field=Field

##
## Initializer Name.
##
Themis.ui.source.decl.init=Initializer

##
## ArrayLevel Name.
##
Themis.ui.source.node.arrayLevel=ArrayLevel

##
## Case Name.
##
Themis.ui.source.node.case=Case

##
## Catch Name.
##
Themis.ui.source.node.catch=Catch

##
## Comment Name.
##
Themis.ui.source.node.comment=Comment

##
## CompilationUnit Name.
##
Themis.ui.source.node.compUnit=CompilationUnit

##
## Import Name.
##
Themis.ui.source.node.import=Import

##
## Name Name.
##
Themis.ui.source.node.name=Name

##
## Package Name.
##
Themis.ui.source.node.package=Package

##
## ValuePair Name.
##
Themis.ui.source.node.valuePair=ValuePair

##
## ArrayAccess Name.
##
Themis.ui.source.expr.arrayAccess=ArrayAccess

##
## Marker Name.
##
Themis.ui.source.expr.marker=MarkerAnnot

##
## Normal Name.
##
Themis.ui.source.expr.normal=NormalAnnot

##
## SingleMember Name.
##
Themis.ui.source.expr.single=SingleAnnot

##
## ArrayCreate Name.
##
Themis.ui.source.expr.arrayCreate=ArrayCreate

##
## Cast Name.
##
Themis.ui.source.expr.cast=Cast

##
## Char Name.
##
Themis.ui.source.expr.char=Char

##
## ArrayInit Name.
##
Themis.ui.source.expr.arrayInit=ArrayInit

##
## Integer Name.
##
Themis.ui.source.expr.int=Integer

##
## Assign Name.
##
Themis.ui.source.expr.assign=Assign

##
## Binary Name.
##
Themis.ui.source.expr.binary=Binary

##
## Boolean Name.
##
Themis.ui.source.expr.boolean=Boolean

##
## Class Name.
##
Themis.ui.source.expr.class=Class

##
## Conditional Name.
##
Themis.ui.source.expr.condition=Conditional

##
## Null Name.
##
Themis.ui.source.expr.null=Null

##
## Double Name.
##
Themis.ui.source.expr.double=Double

##
## Enclosed Name.
##
Themis.ui.source.expr.enclosed=Enclosed

##
## FieldAccess Name.
##
Themis.ui.source.expr.fieldAccess=FieldAccess

##
## InstanceOf Name.
##
Themis.ui.source.expr.instance=InstanceOf

##
## Lambda Name.
##
Themis.ui.source.expr.lambda=Lambda

##
## Long Name.
##
Themis.ui.source.expr.long=Long

##
## MethodCall Name.
##
Themis.ui.source.expr.methodCall=MethodCall

##
## MethodRef Name.
##
Themis.ui.source.expr.methodRef=MethodRef

##
## Name Name.
##
Themis.ui.source.expr.name=Name

##
## ObjectCreate Name.
##
Themis.ui.source.expr.objCreate=ObjectCreate

##
## String Name.
##
Themis.ui.source.expr.string=String

##
## Super Name.
##
Themis.ui.source.expr.super=Super

##
## Switch Name.
##
Themis.ui.source.expr.switch=Switch

##
## TextBlock Name.
##
Themis.ui.source.expr.text=TextBlock

##
## This Name.
##
Themis.ui.source.expr.this=This

##
## Type Name.
##
Themis.ui.source.expr.type=Type

##
## TypePattern Name.
##
Themis.ui.source.expr.typePattern=TypePattern

##
## Unary Name.
##
Themis.ui.source.expr.unary=Unary

##
## Variable Name.
##
Themis.ui.source.expr.var=Variable

##
## Assert Name.
##
Themis.ui.source.stmt.assert=Assert

##
## Block Name.
##
Themis.ui.source.stmt.block=Block

##
## Break Name.
##
Themis.ui.source.stmt.break=Break

##
## Constructor Name.
##
Themis.ui.source.stmt.construct=Constructor

##
## Continue Name.
##
Themis.ui.source.stmt.continue=Continue

##
## Do Name.
##
Themis.ui.source.stmt.do=Do

##
## Empty Name.
##
Themis.ui.source.stmt.empty=Empty

##
## For Name.
##
Themis.ui.source.stmt.for=For

##
## ForEach Name.
##
Themis.ui.source.stmt.forEach=ForEach

##
## If Name.
##
Themis.ui.source.stmt.if=If

##
## Assert Name.
##
Themis.ui.source.stmt.labelled=Labelled

##
## Return Name.
##
Themis.ui.source.stmt.return=Return

##
## Switch Name.
##
Themis.ui.source.stmt.switch=Switch

##
## Synchronised Name.
##
Themis.ui.source.stmt.sync=Synchronized

##
## Throw Name.
##
Themis.ui.source.stmt.throw=Throw

##
## Try Name.
##
Themis.ui.source.stmt.try=Try

##
## While Name.
##
Themis.ui.source.stmt.while=While

##
## Yield Name.
##
Themis.ui.source.stmt.yield=Yield

##
## Array Name.
##
Themis.ui.source.type.array=Array

##
## Class Name.
##
Themis.ui.source.type.class=ClassRef

##
## Intersection Name.
##
Themis.ui.source.type.intersect=Intersection

##
## Parameter Name.
##
Themis.ui.source.type.parameter=Parameter

##
## Primitive Name.
##
Themis.ui.source.type.primitive=Primitive

##
## Union Name.
##
Themis.ui.source.type.union=Union

##
## Unknown Name.
##
Themis.ui.source.type.unknown=Unknown

##
## Var Name.
##
Themis.ui.source.type.var=Var

##
## Void Name.
##
Themis.ui.source.type.void=Void

##
## Wildcard Name.
##
Themis.ui.source.type.wildcard=Wildcard
