/* JavaFX specific */
plugins {
    id 'jOceanus-java'
    id 'jOceanus-javafx'
    id 'org.openjfx.javafxplugin' version "0.1.0"
}

/* Dependencies */
dependencies {
    implementation platform(project(':bom'))
    implementation project(':moneywise-core')
    implementation project(':tethys-javafx')
    implementation project(':tethys-api')
    implementation project(':oceanus')
}

/* Details */
group = 'io.github.tonywasher.joceanus.moneywise'
description = 'MoneyWise Personal Finance - javaFX'
mainClass = "io.github.tonywasher.joceanus.moneywise.ui.javafx.MoneyWise4FX"
moduleName = "io.github.tonywasher.joceanus.moneywise.javafx"
preLoaderClass = "io.github.tonywasher.joceanus.moneywise.ui.javafx.MoneyWiseFXpreLoader"

/* Register the project */
rootProject.registerProject(project)

/* Specific Manifest details */
jar {
    manifest {
        attributes(manifestAttrs)
    }
}
